[package]
name = "reassoc"
description = "Ordinary arithmetic syntax for Rust's algebraic float operators"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
reassoc-macros = { version = "=0.1.0", path = "../reassoc-macros" }

[dev-dependencies]
trybuild = "1.0.120"
