[package]
name = "reassoc-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.3", features = ["full", "visit-mut", "parsing", "printing", "proc-macro"] }
quote = "1.0.47"
proc-macro2 = "1.0.107"
